import type { ScheduleItem } from "./types";

export const gradeFilters = [
  {
    id: "all",
    label: "すべて",
    selectedClassName: "bg-slate-800 text-white",
  },
  {
    id: "kids",
    label: "キッズ",
    selectedClassName: "bg-pink-500 text-white",
  },
  {
    id: "1",
    label: "1年",
    selectedClassName: "bg-red-500 text-white",
  },
  {
    id: "2",
    label: "2年",
    selectedClassName: "bg-orange-500 text-white",
  },
  {
    id: "3",
    label: "3年",
    selectedClassName: "bg-yellow-400 text-slate-900",
  },
  {
    id: "4",
    label: "4年",
    selectedClassName: "bg-green-500 text-white",
  },
  {
    id: "5",
    label: "5年",
    selectedClassName: "bg-blue-500 text-white",
  },
  {
    id: "6",
    label: "6年",
    selectedClassName: "bg-purple-500 text-white",
  },
];

export const schedules: ScheduleItem[] = [
  {
    id: "schedule-1",
    date: "2026-07-04",
    dateLabel: "7月4日（土）",
    gradeId: "1",
    gradeLabel: "1年",
    typeId: "practice",
    typeLabel: "通常練習",
    subTypeId: "",
    subTypeLabel: "",
    placeId: "zuko-school",
    placeLabel: "瑞光小",
    startTime: "08:00",
    endTime: "10:00",
    status: "scheduled",
    belongings: "水筒、ボール、すね当て",
    memo: "開始10分前までに集合してください。",
  },
  {
    id: "schedule-2",
    date: "2026-07-04",
    dateLabel: "7月4日（土）",
    gradeId: "2",
    gradeLabel: "2年",
    typeId: "practice",
    typeLabel: "通常練習",
    subTypeId: "",
    subTypeLabel: "",
    placeId: "zuko-school",
    placeLabel: "瑞光小",
    startTime: "08:00",
    endTime: "10:00",
    status: "scheduled",
    belongings: "水筒、ボール",
    memo: "",
  },
  {
    id: "schedule-3",
    date: "2026-07-04",
    dateLabel: "7月4日（土）",
    gradeId: "3",
    gradeLabel: "3年",
    typeId: "practice",
    typeLabel: "通常練習",
    subTypeId: "",
    subTypeLabel: "",
    placeId: "zuko-school",
    placeLabel: "瑞光小",
    startTime: "10:00",
    endTime: "12:00",
    status: "scheduled",
    belongings: "",
    memo: "",
  },
  {
    id: "schedule-4",
    date: "2026-07-05",
    dateLabel: "7月5日（日）",
    gradeId: "4",
    gradeLabel: "4年",
    typeId: "trm",
    typeLabel: "TRM",
    subTypeId: "",
    subTypeLabel: "",
    placeId: "higashiogu",
    placeLabel: "東尾久グラウンド",
    startTime: "09:00",
    endTime: "12:00",
    status: "scheduled",
    belongings: "",
    memo: "",
  },
  {
    id: "schedule-5",
    date: "2026-07-05",
    dateLabel: "7月5日（日）",
    gradeId: "5",
    gradeLabel: "5年",
    typeId: "trm",
    typeLabel: "TRM",
    subTypeId: "",
    subTypeLabel: "",
    placeId: "higashiogu",
    placeLabel: "東尾久グラウンド",
    startTime: "09:30",
    endTime: "12:00",
    status: "scheduled",
    belongings: "",
    memo: "",
  },
];